# 第11章 期约与异步函数

## 11.1 异步编程

- **同步行为** 对应内存顺序执行的处理器指令

- **异步行为** 类似系统中断，即当前进程外部的实体可以触发代码执行

- 之前的异步编程方式，**使用回调函数表明异步操作完成**

  ```javascript
  function double(value) {
      setTimeout(() => setTimeout(console.log, 0, value * 2), 1000);
  }
  
  double(3);
  ```

  - 返回异步值

    ```javascript
    // 返回异步值
    function double(value, callback) {
        setTimeout(() => callback(value * 2), 1000);
    }
    
    double(3, (x) => console.log(`I was given: ${x}`));
    ```

  - 失败处理

    ```javascript
    // 失败处理
    function double(value, success, failure) {
        setTimeout(() => {
            try {
                if (typeof value !== 'number') {
                    throw 'Must provide number as first argument';  
                }
                success(2 * value);
            } catch (e) {
                failure(e);
            }
        }, 1000);
    }
    
    const successCallback = (x) => console.log(`Success: ${x}`);
    
    const failureCallback = (x) => console.log(`Failure: ${x}`);
    
    double(3, successCallback, failureCallback);
    double('3', successCallback, failureCallback);
    ```

    ![image-20210731231900183](https://i.loli.net/2021/07/31/WnAl4VsmBkzPfMe.png)

  - 异步嵌套回调

    ```javascript
    // 异步嵌套回调
    function double(value, success, failure) {
        setTimeout(() => {
            try {
                if (typeof value !== 'number') {
                    throw 'Must provide number as first argument';
                }
                success(2 * value);
            } catch (e) {
                failure(e);
            }
        }, 1000);  
    }
    
    const successCallback = (x) => {
        double(x, (y) => console.log(`Success: ${y}`));
    };
    
    const failureCallback = (e) => {
        console.log(`Failure: ${e}`);
    };
    
    double(3, successCallback, failureCallback);
    ```

    ![image-20210731234138981](https://i.loli.net/2021/07/31/JBdVOyeHptf9LQ8.png)

## 11.2 期约

**期约 Promise** 是一个对象，它代表了一个异步操作的最终完成或者失败



**本质上 `Promise` 是一个函数返回的对象**，我们可以在它上面 **绑定回调函数**，这样我们就不需要在一开始把回调函数作为参数传入这个函数了



**Promise** 对象用于表示一个异步操作的最终完成 (或失败)及其结果值

- 用途
  - 抽象的表示一个异步操作 期约的状态代表期约是否完成
    - **待定 pending** 表示尚未开始或者正在执行中
    - **兑现 fulfilled** 表示已经成功完成
    - **拒绝 rejected** 表示没有成功完成
  - 期约封装的异步操作会实际生成一个值，程序期待期约状态改变是可以访问这个值，默认值都为 `undefined`
    - 每个期约状态切换成 **兑现**，就会有一个私有的 **内部值**
    - 每个期约状态切换为 **拒绝**，就会有一个私有的内部 **理由**

- 期约的三种状态
  - 待定 pending
  - 兑现 fulfilled
  - 拒绝 rejected

![img](https://i.loli.net/2021/08/04/qVH5jYXrUQz7fnI.png)

- 通过执行函数控制期约状态

  - 执行函数

    - 初始化期约的异步行为
    - 控制状态的最终转换 通过调用控制函数的两个函数参数
      - `resolve() ` 将状态切换为兑现
      - `reject()` 将状态切换为拒绝

    ```javascript
    // 期约
    let p1 = new Promise(
        // 执行器函数
        (resolve, reject) => resolve()
    );
    setTimeout(console.log, 0, p1); // Promise <resolved>
    
    let p2 = new Promise(
    	// 执行器函数
        (resolve, reject) => reject()
    );
    setTimeout(console.log, 0, p2); // Promise <rejected>
    // Uncaught error (in promise)
    ```

- 期约状态只能改变一次

- `Promise.resolve()` 期约并非一开始就必须处于待定pending状态，然后通过执行器函数才能转换为落定 `fulfilled` 状态。通过 `Promise.resolve()` 可以实例化一个解决的期约

  - 多余参数会被忽略

  - 如果传入参数是一个期约，就是一个空包装，相当于一个幂等方法

    ```javascript
    let p = Promise.resolve(1);
    
    console.log(p === Promise.resolve(p))
    ```

  - `Promise.resolve()` 可以包装任何非期约值，包括错误对象，并将其转换为解决的期约

- `Promise.reject()  ` 实例化一个拒绝的期约并跑出一个异步错误（但是这个错误不能被 `try/catch` 捕获，只能通过拒绝处理程序捕获），如果传给其一个期约对象，则这个传入的期约对象就会成为它返回的拒绝期约的理由

  ```javascript
  setTimeout(
      console.log,
      0,
      Promise.reject(Promise.resolve())
  );
  ```

  ![image-20210805205545457](https://i.loli.net/2021/08/05/5GzyZA4BlJ7bTxp.png)

- 期约的实例方法

  - 实现 `Thenable` 接口 ----> `Promise.prototype.then(onResolved, onRejected)` 这两个参数为可选，传给 `then() ` 的任何非函数类型会被自动忽略

    - 不传入 `onResolve()` 处理程序的写法

      ```javascript
      p2.then(null, () => onRejected('p2'));
      ```

    - `then()` 返回一个新的期约实例 这个新期约的实例基于`onRresolved`处理程序的返回值构建

    ```javascript
    function onResolved(id) {
        setTimeout(
            console.log,
            0,
            id,
            'resolved'
        );
    }
    
    function onRejected(id) {
        setTimeout(
            console.log,
            0,
            id,
            'rejected'
        );
    }
    
    let p1 = new Promise(
        (resolve, reject) => {
            setTimeout(
                resolve,
                3000
            );
        }
    )
    
    let p2 = new Promise(
        (resolve, reject) => {
            setTimeout(
                reject,
                3000
            );
        }
    )
    
    p1.then(
        () => {
            onResolved('p1');
        },
        () => {
            onRejected('p1');
        }
    )
    
    p2.then(
        () => {
            onResolved('p2');
        },
        () => {
            onRejected('p2');
        }
    )
    ```

    ![image-20210805210210240](https://i.loli.net/2021/08/05/RbglSw6n8KA4WqP.png)

- `Promise.prototype.catch(onRejected)` 给期约添加拒绝处理程序，参数 `onRejected` 调用 `Promise.prototype.then(null, onRejected)` ，返回一个新的期约实例

  ```javascript
  let p = Promise.reject();
  let onRejected = function(e) {
      setTimeout(
          console.log,
          0,
          'rejected'
      );
  };
  
  p.then(
      null,
      onRejected
  ); // rejected
  
  p.catch(onRejected); // rejected
  ```

- `Promise.prototype.finnaly()` 给期约添加 `onFinally` 处理程序，**这个处理程序在期约转换为解决或拒绝状态是都会执行**，这个方法可以避免`onResolved `和 `onRejected `处理程序中出现冗余代码，但 `onFinally` 无法知道期约的状态，返回一个新的期约实例，这个期约对于已解决状态和被拒绝状态表现为父期约的传递，对待定的期约或者 `onFinally` 处理程序抛出错误，返回相应的期约（待定或拒绝）

- **非重入期约方法** **当期约进入落定状态时，与该状态相关的处理程序会被 排期，而不是立即执行**；跟在添加这个处理程序后的同步代码一定会在处理程序之前执行，即便期约一开始就是与附加处理程序关联的状态，执行顺序也是这样，这个特性被称为 **非重入 non-reentrancy**

  ```javascript
  let p = Promise.resolve();
  
  p.then(
      () => {
          console.log('onResolved handler');
      }
  );
  
  console.log('then() returns');
  ```

  ![image-20210806092524731](https://i.loli.net/2021/08/06/Bvy9Cfrb4Tx7d5X.png)

  下面的例子展示了即使先添加了 `onResolved` 处理程序，在同步调用 `resolve()` ，处理程序也不会进入同步线程执行

  ```javascript
  let synchronousResolve;
  
  let p = new Promise(
      (resolve) => {
          synchronousResolve = function() {
              console.log('1: invoking resolve()');
              resolve();
              console.log('2: resolve() returns');
          };
      }
  );
  
  p.then(
      () => {
          console.log('4: then() handler executes');
      }
  );
  
  synchronousResolve();
  
  console.log('3: synchronousResolve returns');
  ```

  ![image-20210806093034160](https://i.loli.net/2021/08/06/bcHTFIgluQ82Xrm.png)

  非重入适用于 `onResolved/onRejected` 处理程序、`catch()`、`finally()`，下面例子展示了这些处理程序都只能异步执行:

  ```javascript
  let p1 = Promise.resolve();
  p1.then(
      () => {
          console.log('p1.then() onResolved');
      }
  );
  console.log('p1.then() returns');
  
  let p2 = Promise.reject();
  p2.then(
      null,
      () => {
          console.log('p2.then() onRejected');
      }
  );
  console.log('p2.then() returns');
  
  let p3 = Promise.reject();
  p3.catch(
      () => {
          console.log('p3.catch() onRejected');
      }
  );
  console.log('p3.catch() returns');
  
  let p4 = Promise.resolve();
  p4.finally(
      () => {
          console.log('p4.finally() onFinally');
      }
  );
  console.log('p4.finally() returns');
  ```

  ![image-20210806093853239](https://i.loli.net/2021/08/06/SpvAeoq1wKWPGMJ.png)

- 邻近处理程序的执行顺序 如果给期约添加了多个处理程序，当期约状态变化是，相关处理程序会按照添加他们的顺序依次执行

  ```javascript
  let p1 = Promise.resolve();
  let p2 = Promise.reject();
  
  p1.then(
      () => {
          setTimeout(
              console.log,
              0,
              1
          );
      }
  );
  
  p1.then(
      () => {
          setTimeout(
              console.log,
              0,
              2
          );
      }
  );
  
  p2.then(
      null,
      () => {
          setTimeout(
              console.log,
              0,
              3
          )
      }
  );
  
  p2.then(
      null,
      () => {
          setTimeout(
              console.log,
              0,
              4
          )
      }
  );
  
  p2.catch(
      () => {
          setTimeout(
              console.log,
              0,
              5
          )
      }
  );
  
  p2.catch(
      () => {
          setTimeout(
              console.log,
              0,
              6
          )
      }
  );
  
  p2.finally(
      () => {
          setTimeout(
              console.log,
              0,
              7
          )
      }
  );
  
  p2.finally(
      () => {
          setTimeout(
              console.log,
              0,
              8
          )
      }
  );
  ```

  ![image-20210806095046305](https://i.loli.net/2021/08/06/6yLwFB8ACboStN1.png)

- **传递解决值和拒绝理由** 到了落定状态后，期约会提供其解决值（如果兑现）或拒绝理由（如果拒绝）给相关状态的处理程序，在执行函数中，解决的值和拒绝的理由分别作为 `resolve()` 和 `reject()` 的第一个参数后，然后这些值又会传递给它们各自的处理程序，作为 `onResolved` 或 `onRejected` 处理程序唯一参数

  ```javascript
  let p1 = new Promise(
      (resolve, reject) => {
          resolve('foo');
      }
  ); // ==> Promise.resolve('foo')
  p1.then(
      (value) => {
          console.log(value);
      }
  );
  
  let p2 = new Promise(
      (resolve, reject) => {
          reject('bar');
      }
  ); // ==> Promise.reject('bar')
  p2.catch(
      (reason) => {
          console.log(reason);
      }
  );
  ```

  ![image-20210806100140511](https://i.loli.net/2021/08/06/PyxFfLh5nrJXlS7.png)

- **拒绝期约与拒绝错误处理** 拒绝期约类似于 `throw()` 表达式，都表示一种程序状态，**需要中断或特殊处理**。在期约的执行函数或处理程序中抛出错误会导致拒绝，对象的错误对象会成为拒绝的理由。下面的期约都会以一个错误对象为由被拒绝：

  ```javascript
  let p1 = new Promise(
      (resolve, reject) => {
          reject(Error('foo'));
      }
  );
  
  let p2 = new Promise(
      (resolve, reject) => {
          throw Error('foo');
      }
  );
  
  let p3 = Promise.resolve().then(
      () => {
          throw Error('foo');
      }
  );
  
  let p4 = Promise.reject(Error('foo'));
  
  setTimeout(console.log, 0, p1); // Promise <rejected>: Error foo
  setTimeout(console.log, 0, p2); // Promise <rejected>: Error foo
  setTimeout(console.log, 0, p3); // Promise <rejected>: Error foo
  setTimeout(console.log, 0, p4); // Promise <rejected>: Error foo
  ```

  - 期约也可以用任何理由拒绝，包括 `undefined`，但是最好私有错误对象，这样可以让浏览器捕获错误对象中的栈追踪信息

  - 在期约抛出错误时，**错误是从消息队列异步抛出的**，所以并不是阻止运行时继续执行的同步指令

    ```javascript
    Promise.reject(Error('foo'));
    console.log('bar');
    // bar
    
    // Uncaught (in promise) Error: foo
    ```

  - **异步错误只能通过异步的 `onRejected`处 理程序捕获**

    ```javascript
    // 异步错误处理
    new Promise(
        (resolve, reject) => {
            console.log('begin asynchronous execution');
            reject(Error('bar'));
        }
    ).catch(
        (e) => {
            console.log('caught error', e);
        }
    ).then(
        () => {
            console.log('continue asynchronous execution');
        }
    );
    ```

    ![image-20210806102222958](https://i.loli.net/2021/08/06/It2eQmlkLUETnc3.png)

- **期约连锁** 把多个期约串联起来，由于每个期约实例方法（`then() catch() finally()`）都会返回一个新的期约对象，而这个新期约又有自己的实例方法

  ```javascript
  function delayedResolve(str) {
      return new Promise(
          (resolve, reject) => {
              console.log(str);
              setTimeout(resolve, 1000);
          }
      );
  }
  
  delayedResolve('p1 executor')
      .then(() => delayedResolve('p2 executor'))
      .then(() => delayedResolve('p3 executor'))
      .then(() => delayedResolve('p4 executor'))
  ```

  ![image-20210806103217208](https://i.loli.net/2021/08/06/ivC1sfNwnHachLK.png)

  每个后续的处理程序都会等待前一个期约解决，然后实例化一个新期约并返回他，这样可以简洁地将异步任务串行化，解决之前的依赖回调难题

- 期约图 由于期约可以有任意多个处理程序，所以期约连锁可以构建 **有向非循环图**。这样，每个期约都是图中的一个节点，而使用实例方法添加的处理程序则是有向顶点，因为图中的每个节点都等待前一个节点落定，所以图的方向就是期约的解决或拒绝程序

  ```javascript
  //     A
  //    / \
  //   B   C
  //  / \ / \
  // D  E F  G
  
  let A = new Promise(
      (resolve, reject) => {
          console.log('A');
          resolve();
      }
  );
  let B = A.then(() => console.log('B'))
  let C = A.then(() => console.log('C'))
  
  B.then(() => console.log('D'))
  B.then(() => console.log('E'))
  C.then(() => console.log('F'))
  C.then(() => console.log('G'))
  ```

  ![image-20210806104012424](https://i.loli.net/2021/08/06/3c9Cm1opxe4FGaQ.png)

- `Promise.all()` 静态方法创建的期约会在一组期约全部解决后在解决，接收一个可迭代对象，返回一个新期约

  ```javascript
  // Promise.all()
  let p1 = Promise.all(
      [
          Promise.resolve(),
          Promise.resolve()
      ]
  );
  
  let p2 = Promise.all([3, 4]); // 自动转换
  
  let p3 = Promise.all([]); // 等价于 Promise.resolve()
  
  let p4 = Promise.all(); // 无效的语法
  ```

  - 合成的期约只会在每个包含的期约都解决后才解决

    ```javascript
    let p = Promise.all([
        Promise.resolve(),
        new Promise(
            (resolve, reject) => {
                setTimeout(resolve, 1000);
            }
        )
    ]);
    
    setTimeout(console.log, 0, p);
    
    p.then(
        () => {
            setTimeout(console.log, 0, 'all() resolved');
        }
    );
    ```

    ![image-20210806104806974](https://i.loli.net/2021/08/06/wpboKcrJihDMjUB.png)

  - 如果有一个包含的期约拒绝，则合成的期约也会拒绝

  - **如果所有期约都成功解决，则合成期约的解决值就是所有包含期约解决值的数组，按照迭代器顺序**

    ```javascript
    let p = Promise.all([
        Promise.resolve(1),
        Promise.resolve(),
        Promise.resolve(3)
    ]);
    
    p.then(
        (values) => {
            setTimeout(
                console.log,
                0,
                values
            );
        }
    );
    ```

    ![image-20210806105840126](https://i.loli.net/2021/08/06/kL7mQN5hurMaBAS.png)

  - 如果有期约拒绝，则第一个拒绝的期约会将自己的理由作为合成期约的拒绝的理由，之后再拒绝的期约不会影响最终期约的拒绝理由，这不会影响所有包含期约正常的拒绝操作

- `Promise.race()` 返回一个包装期约，**是一组集合中最先解决或拒绝的期约的镜像**，接收一个可迭代对象，返回一个新期约

  - `Promise.race()` 不会对解决或拒绝的期约区别对待，无论是解决还是拒绝，只要是第一个落定的期约，`Promise.race()` 就会包装其解决值或拒绝理由并返回新期约

    ```javascript
    let p1 = Promise.race([
        Promise.resolve(3),
        new Promise(
            (resolve, reject) => {
                setTimeout(reject, 1000);
            }
        )
    ]);
    setTimeout(console.log, 0, p1);
    
    let p2 = Promise.race([
        Promise.reject(4),
        new Promise(
            (resolve, reject) => {
                setTimeout(resolve, 1000);
            }
        )
    ]);
    setTimeout(console.log, 0, p2);
    
    let p3 = Promise.race([
        Promise.resolve(5),
        Promise.resolve(6),
        Promise.resolve(7)
    ]);
    setTimeout(console.log, 0, p3);
    ```

- 串行期约合成  期约的另一个特性：异步产生值并将其传给处理程序。基于后续期约使用之前期约的返回值来串联期约是期约的基本功能

  ```javascript
  function addTwo(x) { return x + 2;}
  function addThree(x) { return x + 3;}
  function addFive(x) { return x + 5;} 
  function addTen0(x) { return addFive(addThree(addTwo(x)));}
  
  function addTen(x) {
      return Promise.resolve(x)
          .then(addTwo)
          .then(addThree)
          .then(addFive);
  }
  
  function addTen2(x) {
      return [addTwo, addThree, addFive]
          .reduce(
              (promise, fn) => promise.then(fn),
              Promise.resolve(x)
          )
  }
  
  function compose(...fns) {
      return (x) => fns.reduce(
          (promise, fn) => promise.then(fn),
          Promise.resolve(x)
      );
  }
  
  let addTen3 = compose(addTwo, addThree, addFive);
  
  addTen(8).then(console.log);
  addTen2(8).then(console.log);
  addTen3(8).then(console.log);
  ```

  ![image-20210808094909372](https://i.loli.net/2021/08/08/umVHdgXnGWkNsDR.png)

- 期约扩展

- 期约进度通知

## 11.3 异步函数

**`async/await`**

- **`async` 声明异步函数，可以用在函数声明、函数表达式、箭头函数、方法**

  ```javascript
  // async
  async function foo() {}
  
  let bar = async function() {};
  
  let baz = async () => {};
  
  class Qux {
      async qux() {}
  }
  ```

  - `async` 关键字可以让 **函数具有异步特征，但总体上代码仍然是同步求值**。在参数或闭包方法，异步函数仍然具有普通JavaScript函数的正常行为

    ```javascript
    async function foo() {
        console.log(1);
    }
    
    foo();
    console.log(2);
    ```

    ![image-20210808113052813](https://i.loli.net/2021/08/08/EVinHJsltWk8YZe.png)

  - 异步函数如果使用 `return` 关键字返回了值（如果没有 `return` 则返回 `undefined` ），**这个返回值会被 `Promise.resolve()` 包装成一个期约对象**。异步函数始终返回期约对象，在函数外部调用这个函数可以得到它返回的期约

    ```javascript
    async function foo() {
        console.log(1);
        return 3;
    }
    
    foo().then(console.log);
    
    console.log(2);
    ```

    ![image-20210808113744283](https://i.loli.net/2021/08/08/wKramJudTpSB3z8.png)

  - 异步函数的返回值期待一个实现 `thenable` 接口的对象，但是常规的值也可以

    - 如果返回的是实现 `thenable` 接口的对象，则这个对象可以由提供给 `then()` 的处理程序解包

    - 如果不是，则返回值就被当做已经解决的期约

      ```javascript
      // 返回一个原始值
      async function foo() {
          return 'foo';
      }
      foo().then(console.log);
      
      // 返回一个没有实现 thenable 接口的对象
      async function bar() {
          return ['bar'];
      }
      bar().then(console.log);
      
      // 返回一个实现了 thenable 对象的非期约对象
      async function baz() {
          const thenable = {
              then(callback) {
                  callback('baz');
              }
          };
          return thenable;
      }
      baz().then(console.log);
      
      // 返回一个期约
      async function qux() {
          return Promise.resolve('qux');
      }
      qux().then(console.log);
      
      // 在异步函数中抛出错误 返回拒绝的期约
      async function quz() {
          console.log(1);
          throw 3;
      }
      quz().catch(console.log);
      console.log(2);
      ```

      ![image-20210808134738749](https://i.loli.net/2021/08/08/fUMD3wvTWjdhiVQ.png)

- **`await` 暂停异步函数代码的执行，等待期约解决，其尝试解包对象的值**，然后将这个值传给表达式，再一步恢复函数的执行，可以单独使用，也可以在表达式中使用

  ```javascript
  async function foo() {
      console.log(await Promise.resolve('foo'));
  }
  foo();
  
  async function bar() {
      return await Promise.resolve('bar');
  }
  bar().then(console.log);
  
  async function baz() {
      await new Promise(
          (resolve, reject) => {
              setTimeout(resolve, 1000);
          }
      );
      console.log('baz');
  }
  baz();
  ```

  ![image-20210808135737901](https://i.loli.net/2021/08/08/82xnaiybv6dYOBj.png)
  - **`await` 关键字必须在异步函数中使用，异步函数的特质不会扩展到嵌套函数**，`await` 关键字也只能直接出现在异步函数的定义中，在同步函数内部使用`await ` 会抛出 `SyntaxError`

  - `async/await` 中真正起作用的是 `await`，`async` 关键字只是一个标识符，异步函数如果不包含 `await`，其执行与普通函数没有区别

    ```javascript
    async function foo() {
        console.log(await Promise.resolve('foo'));
    }
    
    async function bar() {
        console.log(await 'bar');
    }
    
    async function baz() {
        console.log('baz');
    }
    
    foo();
    bar();
    baz();
    ```

    ![image-20210808140609097](https://i.loli.net/2021/08/08/gmAY7hSZBuqLdoM.png)

  - JavaScript 运行时遇到 `await `关键字时，会记录在哪里暂停执行，等到 `await` 右边的值可用了，JavaScript会向消息队列中推送一个任务，这个任务会恢复异步函数的执行。所以，即使 `await` 后面跟着一个立即可用的值，函数的其余部分也会被异步求值

    ```javascript
    async function foo() {
        console.log(2);
        await null;
        console.log(4);
    }
    console.log(1);
    foo();
    console.log(3);
    ```

    ![image-20210808141143504](https://i.loli.net/2021/08/08/f4wkbDXQVPKjCB7.png)

  - 如果 `await` 后面是一个期约，为了执行异步函数，实际上会有两个认为被添加到消息队列并被异步求值

    ```javascript
    async function foo() {
        console.log(2);
        console.log(await Promise.resolve(8));
        console.log(9);
    }
    
    async function bar() {
        console.log(4);
        console.log(await 6);
        console.log(7);
    }
    
    console.log(1);
    foo();
    console.log(3);
    bar();
    console.log(5);
    ```

    ![image-20210808141551679](https://i.loli.net/2021/08/08/yN57meAJ2PGVDSO.png)

- 异步函数策略

  - 实现 `sleep()`

    ```javascript
    // 实现 sleep
    async function sleep(delay) {
        return new Promise(
            (resolve) => {
                setTimeout(resolve, delay);
            }
        );
    }
    
    async function foo() {
        const t0 = Date.now();
        await sleep(1500);
        console.log(Date.now() - t0);
    }
    foo();
    ```

    ![image-20210808141938398](https://i.loli.net/2021/08/08/dIZcaxDusjVHTwr.png)

  - 利用平行执行 就算期约之间没有依赖，异步函数也会一次执行，等待每个超时完成

    ```javascript
    async function randomDelay(id) {
        const delay = Math.random() * 1000;
        return new Promise(
            (resolve) => {
                setTimeout(
                    () => {
                        console.log(`${id} finished`);
                        resolve();
                    },
                    delay
                );
            }
        );
    }
    
    async function foo() {
        const t0 = Date.now();
        for (let i = 0; i < 5; ++i) {
            await randomDelay(i);
        }
    
        console.log(`${Date.now() - t0}ms elapsed`);
    }
    foo();
    ```

    ![image-20210808142836687](https://i.loli.net/2021/08/08/Wr2tViIo5bXHTZK.png)

  - 串行执行期约

    ```javascript
    async function addTwo(x) { 
        console.log(`addTwo: x=${x}`);
        return x + 2;
    }
    async function addThree(x) { 
        console.log(`addThree: x=${x}`);
        return x + 3;
    }
    async function addFive(x) { 
        console.log(`addFive: x=${x}`);
        return x + 5;
    }
    
    async function addTen(x) {
        for (const fn of [addTwo, addThree, addFive]) {
            x = await fn(x);
        }
        return x;
    }
    addTen(9).then(console.log); // 19
    ```

    