# 第21章 错误处理与调试

## 21.1 浏览器错误报告

所有主流桌面浏览器，包括 IE/Edge、 Firefox、 Safari、 Chrome 和 Opera，都提供了向用户报告错误的机制。默认情况下，所有浏览器都会隐藏错误信息。一个原因是除了开发者之外这些信息对别人没什么用，另一个原因是网页在正常操作中报错的固有特性。  

### 21.1.1 桌面控制台

### 21.1.2 移动控制台

## 21.2 错误处理

### 21.2.1 `try/catch` 语句

- 任何可能出错的代码都应该放到 try 块中，而处理错误的代码则放在 catch 块中  
- 如果 try 块中有代码发生错误，代码会立即退出执行，并跳到 catch 块中。 catch 块此时接收到一个对象，该对象包含发生错误的相关信息。与其他语言不同，即使在 catch 块中不使用错误对象，也必须为它定义名称。错误对象中暴露的实际信息因浏览器而异，但至少包含保存错误消息的 message属性。 ECMA-262 也指定了定义错误类型的 name 属性，目前所有浏览器中都有这个属性。

1. **`finally` 子句**

   try/catch 语句中可选的 finally 子句始终运行。如果 try 块中的代码运行完，则接着执行finally 块中的代码。如果出错并执行 catch 块中的代码，则 finally 块中的代码仍执行。 try 或catch 块无法阻止 finally 块执行，包括 return 语句  

   **注意 只要代码中包含了 finally 子句， try 块或 catch 块中的 return 语句就会被忽略**  

2. **错误类型**

   1. `Error`
   2. `InternalError`
   3. `EvalError`
   4. `RangeError`
   5. `ReferenceError`
   6. `SyntaxError`
   7. `TypeError`
   8. `URIError`

   Error 是基类型，其他错误类型继承该类型。因此，所有错误类型都共享相同的属性 。浏览器很少会抛出 Error 类型的错误，该类型主要用于开
   发者抛出自定义错误  

   - **InternalError 类型**的错误会在底层 JavaScript 引擎抛出异常时由浏览器抛出。例如，递归过多导致了栈溢出。这个类型并不是代码中通常要处理的错误，如果真发生了这种错误，很可能代码哪里弄错了或者有危险了。  
   - EvalError 类型的错误会在使用 eval()函数发生异常时抛出。 ECMA-262 规定，“如果 **eval 属性没 有 被 直 接 调 用** （ 即 没 有 将 其 名 称 作 为 一 个 Identifier ， 也 就 是 CallExpression 中 的MemberExpression），或者如果 eval 属性被赋值”，就会抛出该错误。基本上，只要不把 eval()当成函数调用就会报告该错误  
   - RangeError 错误会在数值越界时抛出  
   - ReferenceError 会在找不到对象时发生。（这就是著名的"object expected"浏览器错误的原因。）这种错误经常是由访问不存在的变量而导致的  
   - TypeError 在 JavaScript 中很常见，主要发生在变量不是预期类型，或者访问不存在的方法时。很多原因可能导致这种错误，尤其是在使用类型特定的操作而变量类型不对时。  
   - 最后一种错误类型是 URIError，只会在使用 encodeURI()或 decodeURI()但传入了格式错误的URI 时发生  

   不同的错误类型可用于为异常提供更多信息，以便实现适当的错误处理逻辑。在 try/catch 语句的 catch 块中，可以使用 instanceof 操作符确定错误的类型  

3. **`try/catch` 用法**

   当 try/catch 中发生错误时，浏览器会认为错误被处理了，因此就不会再使用本章前面提到的机制报告错误。如果应用程序的用户不懂技术，那么他们即使看到错误也看不懂，这是一个理想的结果。使用 try/catch 可以针对特定错误类型实现自定义的错误处理。  

   try/catch 语句最好用在自己无法控制的错误上。 例如， 假设你的代码中使用了一个大型 JavaScript库的某个函数，而该函数可能会有意或由于出错而抛出错误。因为不能修改这个库的代码，所以为防止这个函数报告错误，就有必要通过 try/catch 语句把该函数调用包装起来，对可能的错误进行处理。  

   

   如果你明确知道自己的代码会发生某种错误，那么就不适合使用 try/catch 语句。例如，如果给函数传入字符串而不是数值时就会失败，就应该检查该函数的参数类型并采取相应的操作。这种情况下，没有必要使用 try/catch 语句。  

### 21.2.2 抛出错误

与 try/catch 语句对应的一个机制是 throw 操作符，用于在任何时候抛出自定义错误。 throw 操作符必须有一个值，但值的类型不限 ，下面这些代码都是有效的：  

```javascript
throw 12345;
throw "Hello world!";
throw true;
throw { name: "JavaScript" };
```

使用 throw 操作符时，代码立即停止执行，除非 try/catch 语句捕获了抛出的值。  

可以通过内置的错误类型来模拟浏览器错误。每种错误类型的构造函数都只接收一个参数，就是错误消息。  

**自定义错误常用的错误类型是 Error、 RangeError、 ReferenceError 和 TypeError。**

  此外，通过继承 Error（第 6 章介绍过继承）也可以创建自定义的错误类型。创建自定义错误类型时，需要提供 name 属性和 message 属性，比如：  

```javascript
class CustomError extends Error {
    constructor(message) {
        super(message);
        this.name = 'CustomError';
        this.message = message;
    }
}

throw new CustomError('My Message');
```

1. **何时抛出错误**

   抛出自定义错误是解释函数为什么失败的有效方式。在出现已知函数无法正确执行的情况时就应该抛出错误。换句话说，浏览器会在给定条件下执行该函数时抛出错误。例如，下面的函数会在参数不是数组时抛出错误： 
    ```javascript
function process(values) {
       values.sort();
       
       for (const value of values) {
           if (value > 100) {
               return value;
           }
       }
       
       return -1;
   }
    ```
   
   如果给这个函数传入字符串，调用 sort()函数就会失败。每种浏览器对此都会给出一个模棱两可的错误消息，如下所示。
   
   - IE: 属性或方法不存在
   - Firefox：values.sort() 不是函数
   - Safari：值 undefined（对表达式 values.sort 求值的结果）不是一个对象  
   - Chrome: 对象名没有方法'sort'  
   - Opera: 类型不匹配（通常是在需要对象时使用了非对象值）  


2. **抛出错误与`try/catch`**

   一个常见的问题是何时抛出错误，何时使用 try/catch 捕获错误。一般来说，**错误要在应用程序架构的底层抛出**，在这个层面上，人们对正在进行的流程知之甚少，因此无法真正地处理错误。如果你在编写一个可能用于很多应用程序的 JavaScript 库，或者一个会在应用程序的很多地方用到的实用函数，那么应该认真考虑抛出带有详细信息的错误。然后捕获和处理错误交给应用程序就行了。  

   至于抛出错误与捕获错误的区别，可以这样想：应该只在确切知道接下来该做什么的时候捕获错误。**捕获错误的目的是阻止浏览器以其默认方式响应；抛出错误的目的是为错误提供有关其发生原因的说明。**  

### 21.2.3 error 事件

任何没有被 try/catch 语句处理的错误都会在 window 对象上触发 error 事件。该事件是浏览器早期支持的事件，为保持向后兼容，很多浏览器保持了其格式不变。在 onerror 事件处理程序中，任何浏览器都不会传入 event 对象。相反，**会传入 3 个参数：错误消息、发生错误的 URL 和行号**。大多数情况下，只有错误消息有用，因为 URL 就是当前文档的地址，而行号可能指嵌入 JavaScript 或外部文件中的代码。另外， onerror 事件处理程序需要使用 DOM Level 0 技术来指定，因为它不遵循 DOM Level 2 Events标准格式：  

```javascript
// error 事件
window.onerror = (message, url, line) => {
    console.log(message);
};
```

在任何错误发生时，无论是否是浏览器生成的，都会触发 error 事件并执行这个事件处理程序。然后，浏览器的默认行为就会生效，像往常一样显示这条错误消息。可以返回 false 来阻止浏览器默认报告错误的行为，如下所示：  

```javascript
// error 事件
window.onerror = (message, url, line) => {
    console.log(message);
    return false;
};
```

通过返回 false，这个函数实际上就变成了整个文档的 try/catch 语句，可以捕获所有未处理的运行时错误。这个事件处理程序应该是处理浏览器报告错误的最后一道防线。理想情况下，最好永远不要用到。适当使用 try/catch 语句意味着不会有错误到达浏览器这个层次，因此也就不会触发 error事件。  



图片也支持 error 事件。任何时候，如果图片 src 属性中的 URL 没有返回可识别的图片格式，就会触发 error 事件。这个事件遵循 DOM 格式，返回一个以图片为目标的 event 对象。下面是个例子：  

```javascript
const image = new Image();

image.addEventListener('load', (e) => {
    console.log('Image loaded');
});

image.addEventListener('error', (e) => {
    console.log('Image not loaded');
});

image.src = 'doesnotexist.gif';
```

在这个例子中，图片加载失败后会显示一个 alert 警告框。这里的关键在于，当 error 事件发生时，图片下载过程已结束，不会再恢复。  

#### 21.2.4 错误处理策略

过去， Web 应用程序的错误处理策略基本上是在服务器上落地。错误处理策略涉及很多错误和错误处理考量，包括日志记录和监控系统。这些主要是为了分析模式，以期找到问题的根源并了解有多少用户会受错误影响  

在 Web 应用程序的 JavaScipt 层面落地错误处理策略同样重要。 因为任何 JavaScript 错误都可能导致网页无法使用，所以理解这些错误会在什么情况下发生以及为什么会发生非常重要。绝大多数 Web 应用程序的用户不懂技术，在碰到页面出问题时通常会迷惑。为解决问题，他们可能会尝试刷新页面，也可能会直接放弃。作为开发者，应该非常清楚自己的代码在什么情况下会失败，以及失败会导致什么结果。另外，还要有一个系统跟踪这些问题。  

### 21.2.5 识别错误

错误处理非常重要的部分是首先识别错误可能会在代码中的什么地方发生。因为 JavaScript 是松散类型的，不会验证函数参数，所以很多错误只有在代码真正运行起来时才会出现。通常，需要注意 3 类错误：  

- 类型转换错误
- 数据类型错误
- 通信错误

## 21.3 调试技术

### 21.3.1 把消息记录到控制台

所有主流浏览器都有 JavaScript 控制台，该控制台可用于查询 JavaScript 错误。另外，这些浏览器都支持通过 console 对象直接把 JavaScript 消息写入控制台，这个对象包含如下方法。  

- `error(message)`  错误
- `info(message) ` 信息性
- `log(message)` 常规
- `warn(message)`  警告

记录消息时使用的方法不同，消息显示的样式也不同。错误消息包含一个红叉图标，而警告消息包含一个黄色叹号图标。  

### 21.3.2 理解控制台运行时

浏览器控制台是个读取求值打印循环（ REPL， read-eval-print-loop），与页面的 JavaScript 运行时并发。这个运行时就像浏览器对新出现在 DOM 中的<script>标签求值一样。在控制台中执行的命令可以像页面级 JavaScript 一样访问全局和各种 API。控制台中可以执行任意数量的代码，与它可能会阻塞的任何页面级代码一样。修改、对象和回调都会保留在 DOM 和运行时中。  

JavaScript 运行时会限制不同窗口可以访问哪些内容，因而在所有主流浏览器中都可以选择在哪个窗口中执行 JavaScript 控制台输入。你所执行的代码不会有特权提升，仍会受跨源限制和其他浏览器施加的控制规则约束。  

控制台运行时也会集成开发者工具，提供常规 JavaScript 开发中所没有的上下文调试工具。其中一个非常有用的工具是最后点击选择器，所有主流浏览器都会提供。在开发者工具的 Element（元素）标签页内，单击 DOM 树中一个节点，就可以在 Console（控制台）标签页中使用$0 引用该节点的 JavaScript实例。它就跟普通的 JavaScript 实例一样，因此可以读取属性（如$0.scrollWidth），或者调用成员方法（如$0.remove()）。  

### 21.3.3 使用 JavaScript 调试器

在所有主流浏览器中都可以使用的还有 JavaScript 调试器。 ECMAScript 5.1 规范定义了 **debugger关键字**，用于调用可能存在的调试功能。如果没有相关的功能，这条语句会被简单地跳过。可以像下面这样使用 debugger 关键字：  

```javascript
function pauseExecution() {
    console.log('Will print before breakpoint');
    debugger
    console.log('Will not print until breakpoint continues');
}
```

在运行时碰到这个关键字时，所有主流浏览器都会打开开发者工具面板，并在指定位置显示断点。然后，可以通过单独的浏览器控制台在断点所在的特定词法作用域中执行代码。此外，还可以执行标准的代码调试器操作（单步进入、单步跳过、继续，等等）。  

浏览器也支持在开发者工具的源代码标签页中选择希望设置断点的代码行来手动设置断点（不使用debugger 关键字）。这样设置的断点与使用 debugger 关键字设置的一样，只是不会在不同浏览器会话之间保持。  

### 21.3.4 在页面中打印消息

另一种常见的打印调试消息的方式是把消息写到页面中指定的区域。这个区域可以是所有页面中都包含的元素，但仅用于调试目的；也可以是在需要时临时创建的元素。例如，可以定义这样 log()函数：  

```javascript
// 在页面中打印消息
function log(message) {
    // 这个函数的词法作用域会使用这个实例
    // 而不是 window.console
    const console = document.getElementById("debuginfo");
    if (console === null) {
        console = document.createElement("div");
        console.id = "debuginfo";
        console.style.background = "#dedede";
        console.style.border = "1px solid silver";
        console.style.padding = "5px";
        console.style.width = "400px";
        console.style.position = "absolute";
        console.style.right = "0px";
        console.style.top = "0px";
        document.body.appendChild(console);
    }
    console.innerHTML += '<p> ${message}</p>';
}
```

在这个 log()函数中，代码先检测是否已创建了调试用的元素。如果没有，就创建一个新<div>元素并给它添加一些样式，以便与页面其他部分区分出来。此后，再使用 innerHTML 属性把消息写到这个<div>中。结果就是在页面的一个小区域内显示日志信息。  

### 21.3.5 补充控制台方法

console 是一个全局对象，所以可以为这个对象添加方法，也可以用自定义的函数重写已有的方法，这样无论在哪里用到的日志打印方法，都会按照自定义的方式行事。  